// <auto-generated />
using System;
using BarberMe.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberMe.Database.Migrations
{
    [DbContext(typeof(BarberMeDbContext))]
    [Migration("20260718165700_ImproveDatabaseConstraints")]
    partial class ImproveDatabaseConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarberMe.Database.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AppointmentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<int>("BarberServiceId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CancelledById")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompletedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentStatusId");

                    b.HasIndex("BarberServiceId");

                    b.HasIndex("CancelledById");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompletedById");

                    b.HasIndex("ConfirmedById");

                    b.HasIndex("BarberId", "StartDateTime", "EndDateTime");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BarberMe.Database.Models.AppointmentStatus", b =>
                {
                    b.Property<int>("AppointmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AppointmentStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppointmentStatuses");

                    b.HasData(
                        new
                        {
                            AppointmentStatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            AppointmentStatusId = 2,
                            Name = "Confirmed"
                        },
                        new
                        {
                            AppointmentStatusId = 3,
                            Name = "Cancelled"
                        },
                        new
                        {
                            AppointmentStatusId = 4,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.BarberLevel", b =>
                {
                    b.Property<int>("BarberLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarberLevelId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("BarberLevelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BarberLevels");

                    b.HasData(
                        new
                        {
                            BarberLevelId = 1,
                            IsActive = true,
                            Name = "Junior"
                        },
                        new
                        {
                            BarberLevelId = 2,
                            IsActive = true,
                            Name = "Senior"
                        },
                        new
                        {
                            BarberLevelId = 3,
                            IsActive = true,
                            Name = "Master"
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.BarberService", b =>
                {
                    b.Property<int>("BarberServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarberServiceId"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("BarberServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BarberId", "ServiceId")
                        .IsUnique();

                    b.ToTable("BarberServices", t =>
                        {
                            t.HasCheckConstraint("CK_BarberService_DurationMinutes", "[DurationMinutes] > 0");

                            t.HasCheckConstraint("CK_BarberService_Price", "[Price] > 0");
                        });

                    b.HasData(
                        new
                        {
                            BarberServiceId = 1,
                            BarberId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 30,
                            Price = 25m,
                            ServiceId = 1
                        },
                        new
                        {
                            BarberServiceId = 2,
                            BarberId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 20,
                            Price = 15m,
                            ServiceId = 2
                        },
                        new
                        {
                            BarberServiceId = 3,
                            BarberId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 50,
                            Price = 35m,
                            ServiceId = 3
                        },
                        new
                        {
                            BarberServiceId = 4,
                            BarberId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 25,
                            Price = 20m,
                            ServiceId = 4
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NewsId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BarberMe.Database.Models.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NotificationTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = 1,
                            Name = "Reservation"
                        },
                        new
                        {
                            NotificationTypeId = 2,
                            Name = "Reminder"
                        },
                        new
                        {
                            NotificationTypeId = 3,
                            Name = "Payment"
                        },
                        new
                        {
                            NotificationTypeId = 4,
                            Name = "News"
                        },
                        new
                        {
                            NotificationTypeId = 5,
                            Name = "Cancellation"
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PaymentId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("PaymentStatusId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Amount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PaymentStatuses");

                    b.HasData(
                        new
                        {
                            PaymentStatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            PaymentStatusId = 2,
                            Name = "Completed"
                        },
                        new
                        {
                            PaymentStatusId = 3,
                            Name = "Refunded"
                        },
                        new
                        {
                            PaymentStatusId = 4,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.Recommendation", b =>
                {
                    b.Property<int>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("WasAccepted")
                        .HasColumnType("bit");

                    b.HasKey("RecommendationId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("BarberMe.Database.Models.RecommendationFeedback", b =>
                {
                    b.Property<int>("RecommendationFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecommendationFeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.HasKey("RecommendationFeedbackId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("RecommendationFeedbacks", t =>
                        {
                            t.HasCheckConstraint("CK_RecommendationFeedback_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.Refund", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RefundId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Refunds", t =>
                        {
                            t.HasCheckConstraint("CK_Refund_Amount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("BarberId");

                    b.HasIndex("ClientId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            IsActive = true,
                            Name = "Barber"
                        },
                        new
                        {
                            RoleId = 3,
                            IsActive = true,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("DefaultDurationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services", t =>
                        {
                            t.HasCheckConstraint("CK_Service_DefaultDurationMinutes", "[DefaultDurationMinutes] > 0");

                            t.HasCheckConstraint("CK_Service_DefaultPrice", "[DefaultPrice] > 0");
                        });

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            DefaultDurationMinutes = 30,
                            DefaultPrice = 25m,
                            Description = "Classic men's haircut.",
                            IsActive = true,
                            Name = "Haircut"
                        },
                        new
                        {
                            ServiceId = 2,
                            DefaultDurationMinutes = 20,
                            DefaultPrice = 15m,
                            Description = "Beard shaping and trimming.",
                            IsActive = true,
                            Name = "Beard Trim"
                        },
                        new
                        {
                            ServiceId = 3,
                            DefaultDurationMinutes = 50,
                            DefaultPrice = 35m,
                            Description = "Haircut with beard trimming and styling.",
                            IsActive = true,
                            Name = "Haircut & Beard"
                        },
                        new
                        {
                            ServiceId = 4,
                            DefaultDurationMinutes = 25,
                            DefaultPrice = 20m,
                            Description = "Haircut for children.",
                            IsActive = true,
                            Name = "Kids Haircut"
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.SupportRequest", b =>
                {
                    b.Property<int>("SupportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportRequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SupportRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("SupportRequests", t =>
                        {
                            t.HasCheckConstraint("CK_SupportRequest_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("BarberLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequirePasswordChange")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TemporaryPasswordExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("BarberLevelId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@barberme.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            IsActive = true,
                            IsLocked = false,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$3imUFH1O5lE9g7XuS3hZOOUVPwdRz4yQjbw/4pyzVIeXf/ZHTbBUu",
                            PhoneNumber = "000000000",
                            RequirePasswordChange = false,
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            BarberLevelId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "barber@barberme.com",
                            FailedLoginAttempts = 0,
                            FirstName = "John",
                            IsActive = true,
                            IsLocked = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$3imUFH1O5lE9g7XuS3hZOOUVPwdRz4yQjbw/4pyzVIeXf/ZHTbBUu",
                            PhoneNumber = "061111111",
                            RequirePasswordChange = false,
                            RoleId = 2,
                            Username = "barber"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@barberme.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Jane",
                            IsActive = true,
                            IsLocked = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$3imUFH1O5lE9g7XuS3hZOOUVPwdRz4yQjbw/4pyzVIeXf/ZHTbBUu",
                            PhoneNumber = "062222222",
                            RequirePasswordChange = false,
                            RoleId = 3,
                            Username = "client"
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.WorkingHours", b =>
                {
                    b.Property<int>("WorkingHoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkingHoursId"));

                    b.Property<int>("BarberId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("WorkingHoursId");

                    b.HasIndex("BarberId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkingHours");

                    b.HasData(
                        new
                        {
                            WorkingHoursId = 1,
                            BarberId = 2,
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            IsWorking = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            WorkingHoursId = 2,
                            BarberId = 2,
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            IsWorking = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            WorkingHoursId = 3,
                            BarberId = 2,
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            IsWorking = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            WorkingHoursId = 4,
                            BarberId = 2,
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            IsWorking = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            WorkingHoursId = 5,
                            BarberId = 2,
                            DayOfWeek = 5,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            IsWorking = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            WorkingHoursId = 6,
                            BarberId = 2,
                            DayOfWeek = 6,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            IsWorking = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            WorkingHoursId = 7,
                            BarberId = 2,
                            DayOfWeek = 0,
                            EndTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsWorking = false,
                            StartTime = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("BarberMe.Database.Models.Appointment", b =>
                {
                    b.HasOne("BarberMe.Database.Models.AppointmentStatus", "AppointmentStatus")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.User", "Barber")
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.BarberService", "BarberService")
                        .WithMany()
                        .HasForeignKey("BarberServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.User", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarberMe.Database.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.User", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarberMe.Database.Models.User", "ConfirmedBy")
                        .WithMany()
                        .HasForeignKey("ConfirmedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppointmentStatus");

                    b.Navigation("Barber");

                    b.Navigation("BarberService");

                    b.Navigation("CancelledBy");

                    b.Navigation("Client");

                    b.Navigation("CompletedBy");

                    b.Navigation("ConfirmedBy");
                });

            modelBuilder.Entity("BarberMe.Database.Models.BarberService", b =>
                {
                    b.HasOne("BarberMe.Database.Models.User", "Barber")
                        .WithMany("BarberServices")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.Service", "Service")
                        .WithMany("BarberServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Notification", b =>
                {
                    b.HasOne("BarberMe.Database.Models.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Payment", b =>
                {
                    b.HasOne("BarberMe.Database.Models.Appointment", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("BarberMe.Database.Models.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Recommendation", b =>
                {
                    b.HasOne("BarberMe.Database.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberMe.Database.Models.RecommendationFeedback", b =>
                {
                    b.HasOne("BarberMe.Database.Models.Recommendation", "Recommendation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Refund", b =>
                {
                    b.HasOne("BarberMe.Database.Models.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Review", b =>
                {
                    b.HasOne("BarberMe.Database.Models.Appointment", "Appointment")
                        .WithOne("Review")
                        .HasForeignKey("BarberMe.Database.Models.Review", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.User", "Barber")
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberMe.Database.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Barber");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BarberMe.Database.Models.SupportRequest", b =>
                {
                    b.HasOne("BarberMe.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberMe.Database.Models.User", b =>
                {
                    b.HasOne("BarberMe.Database.Models.BarberLevel", "BarberLevel")
                        .WithMany("Users")
                        .HasForeignKey("BarberLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarberMe.Database.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BarberLevel");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BarberMe.Database.Models.WorkingHours", b =>
                {
                    b.HasOne("BarberMe.Database.Models.User", "Barber")
                        .WithMany("WorkingHours")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barber");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Appointment", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("BarberMe.Database.Models.AppointmentStatus", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BarberMe.Database.Models.BarberLevel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BarberMe.Database.Models.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("BarberMe.Database.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Recommendation", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BarberMe.Database.Models.Service", b =>
                {
                    b.Navigation("BarberServices");
                });

            modelBuilder.Entity("BarberMe.Database.Models.User", b =>
                {
                    b.Navigation("BarberServices");

                    b.Navigation("WorkingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
