<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Service\**" />
    <EmbeddedResource Remove="Service\**" />
    <None Remove="Service\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.2" />
    <PackageReference Include="Stripe.net" Version="52.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BarberMe.Database\BarberMe.Database.csproj" />
    <ProjectReference Include="..\BarberMe.Model.SearchObjects\BarberMe.Model.SearchObjects.csproj" />
    <ProjectReference Include="..\BarberMe.Model.Responses\BarberMe.Model.Responses.csproj" />
    <ProjectReference Include="..\BarberMe.Model.Requests\BarberMe.Model.Requests.csproj" />
    <ProjectReference Include="..\BarberMe.Model\BarberMe.Model.csproj" />
  </ItemGroup>

</Project>
